title: Crew
email: hi@crew.lk
description: > # this means to ignore newlines until "baseurl:"
  We are an open innovation business based in Sri Lanka. We are free and open thinking technology professionals working as a tight-knit team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crew.lk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: crewlogic
linkedin_username: crewlogic
facebook_username:  crewlogic
instagram_username:  crewlogic
github_username:  crewlogic

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - amp-jekyll
  - jekyll-analytics
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
minima:
  date_format: "%b %-d, %Y"


header_pages:
- services.md
- careers.md
- posts.md
- about.md
- contact.md

google_analytics: UA-131920458-1

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-131920458-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking



collections:
  services:
    output: true
  careers:
    output: true

